### PR TITLE
Explain swarm limitations (--net=host), remove docker-compose

### PR DESCRIPTION
**Pull request by aymanosman**
Good news, it looks like a PR has landed that will potentially support `--net=host` in swarm. https://github.com/moby/moby/pull/32981

Not sure about the wording but the main thrust of the PR is to revoke support for `--net=some-isolated-network` in both its docker-compose and docker-swarm flavours.

### CODE REVIEW

**Comment by tomashley** [comment]
We could add a section re: `if on isolated network`,  you'll get container discovery, but very likely no metrics for any container

**Comment by tomashley** [comment]
image

**Review by tomashley — APPROVED** [review]

**Comment by thaJeztah** [comment]
@tomashley note that `--network host` is now supported for swarm services (I think since docker 17.06.1) though https://github.com/moby/moby/pull/32981 (see https://github.com/moby/moby/issues/25873#issuecomment-319109840); both of these should now work:


```bash
docker service create --network host --name hostie nginx:alpine
```

```yaml
version: '3.3'

services:
  web:
    image: "nginx:alpine"
    networks:
      - outside

networks:
  outside:
    external:
      name: "host"
```

**Comment by tomashley** [comment]
thanks @thaJeztah I shall give it a try.

**Pull request merged**
